### ISSUE TITLE
verifyClient

### ISSUE THREAD

**Issue by jschimmoeller** [lukeed/sockette#1]
i seen this on twitter and looked very promising.  So did a quick look and dont see support for verifyClient;  use this to validate the ws has the json web token (JWT).  see documentation at: 
https://github.com/websockets/ws/blob/master/doc/ws.md

**Comment by jschimmoeller** [comment]
never mind ... client side ... was thinking server side

**Comment by lukeed** [comment]
Hey, thanks! That's for the Server only, right?

**Comment by lukeed** [comment]
Haha, okay cool. Thanks 😄
