### ISSUE TITLE
Is there a way to tell if reconnection attempts are over?

### ISSUE THREAD

**Issue by alshakero** [lukeed/sockette#11]
Hi! I loved your lib right away!

I have a question, is there a way to tell if max attempts are reached and it will no longer reconnect? Something like `ws.isExhausted` or `ws.doneTrying`? We have HTTP failover in our apps and I would like to only failover after Sockette is exhausted. 

If there isn't such a flag I'd be glad to PR.

Cheers

**Comment by lukeed** [comment]
Hey, thanks! 🙌 

Good call -- are you looking for a callback or would a `ws.*` property be enough? I would think that a callback fits more inline with the rest & is easier to control.

**Comment by lukeed** [comment]
Closed in 712defb83d32e5bc4c3cc73314e32980639996c1 😄
