### ISSUE TITLE
Heartbeat mechanism to detect connection

### ISSUE THREAD

**Issue by outaTiME** [lukeed/sockette#15]
Hi pal, 
it will be great to have heartbeat mechanism (optional) like ping / pong to check the connection availability, what do you think? 

Of course we need special pong message from server (this is why feature must be optional).

Thanks !!!

**Comment by lukeed** [comment]
Heya,

This should be completely custom to your own app and it's impossible to add that to Sockette while (a) covering a wide range of uses and (b) staying below 350 bytes.

You could easily add a `setInterval` once a connection has been established and then apply some teardown logic later on. 

Thanks for the suggestion! :raised_hands: Maybe another module that builds on top of this one, but I think Sockette is complete as is.
