### ISSUE TITLE
TypeError: "Sockette is not a constructor" (Angular/TypeScript)

### ISSUE THREAD

**Issue by TheSpiciestDev** [lukeed/sockette#19]
I've created a new Angular project using the Angular CLI and have installed and attempted to import Sockette into my project (an empty Angular project.)

I am getting the below error when trying to import/require Sockette.
```
TypeError: "Sockette is not a constructor"
```

1. Via `import` gets me the above error:
```typescript
import {Component} from '@angular/core';
import {environment} from '../environments/environment';

import * as Sockette from 'sockette';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor() {
    const socket = new Sockette(environment.websocket_server);
  }
}
```

2. Via `require` gets me the same error above:
```typescript
import {Component} from '@angular/core';
import {environment} from '../environments/environment';

const Sockette = require('sockette');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor() {
    const socket = new Sockette(environment.websocket_server);
  }
}
```

When I `console.log` the Sockette object, I get the following:
```typescript
import {Component} from '@angular/core';
import {environment} from '../environments/environment';

const Sockette = require('sockette');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor() {
    console.log(Sockette);
    const socket = new Sockette(environment.websocket_server);
  }
}
```
```
Object { default: default(), … }
```

Which lead me to try the following (which works!)
```typescript
import {Component} from '@angular/core';
import {environment} from '../environments/environment';

const Sockette = require('sockette');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor() {
    const socket = new Sockette.default(environment.websocket_server);
  }
}
```
I'm left assuming this is due to the way Sockette is being exported... any thoughts?

**Comment by lukeed** [comment]
Hey,

It actually has to be like this:

```js
import Sockette from 'sockette'
```

And because you're using a bundler tool, the `require` statement doesn't work. Bundlers will typically still read from the "module" entry if it's found in the definition.

**Comment by TheSpiciestDev** [comment]
Your example worked!.. thank you again for the direction! I've got enough up and going now to include in my projects - happy to have found you via JavaScript Weekly!

**Comment by lukeed** [comment]
Haha happy to have helped!

**Comment by etw3gh** [comment]
I'm getting the same error regardless if I use `import Sockette from 'sockette'`

**Comment by lukeed** [comment]
@etcraftdelivery This error depends on your build tools. Something probably configured incorrectly, which means that the wrong file is being imported and/or your interop layer is (re)wrapping things it shouldn't.

If you `console.log(Sockette)` you should see a `function`. Again, depending on your config, it might end up looking like `{ default: function }` instead.

**Comment by etw3gh** [comment]
I was getting a string: filepath ending in .mjs after console.log. I'm thinking its a webpack thing. thanks.

**Comment by lukeed** [comment]
Ah, yeah certainly is. You've not even loaded Sockette yet.
