### ISSUE TITLE
onmaximum not triggering

### ISSUE THREAD

**Issue by GMchris** [lukeed/sockette#23]
Am I misunderstanding this method or is it not working?

```javascript
socket = new Sockette(action.url, {
        timeout: 5000,
        maxAttempts: 2,
        onopen: onOpen(store),
        onclose: onClose(store),
        onmessage: onMessage(store),
        onmaximum: onMaximum(store),
        onreconnect: onReconnect(store),
        onerror: noop,
      });
```
I have this snippet setup. Everything works as expected. When the WS server is down, Sockette tries to connect twice, before giving up, however the `onmaximum` callback is never triggered.

**Comment by lukeed** [comment]
Hey, what if you `console.log` out the event listeners?

I've done that just now to re-verify & the `onmaximum` callback is triggered correctly.

**Comment by DarcyXf** [comment]
`
	$.onopen = e => {
		num=0; (opts.onopen || noop)(e);
	};
`
There should't do `num = 0`, otherwise, `num` will lose the original purpose as a global counter

**Comment by xuzeshen** [comment]
$.onopen = e => { num=0; (opts.onopen || noop)(e); };
There should't do num = 0, otherwise, num will lose the original purpose as a global counter
@lukeed @GMchris

**Comment by lukeed** [comment]
@DarcyXf It isn't meant to be global. The `onopen` callback is only called when the connection has been _successfully_ established. We reset the `num` counter because we want to allow `maxAttempts` for every new reconnection.

For example, with a `maxAttempts` of 3 and without resetting every successful connection, this would be the series of events:

```
new Sockette({ maxAttempts:3, timeout:1000 })
//=> 0

*server shutdown*

*wait 1s*
*attempt*
//=> 1

*wait 1s*
*attempt*
//=> 2

*RECONNECTED*
//=> 2

*server shutdown*

*wait 1s*
*attempt*
//=> 3

*GIVE UP FOREVER*
```

Instead, we'd want try again 3 times per connection failure.

**Comment by lukeed** [comment]
If you have any more insight for this @GMchris please let me know – I know it's been a while but it'd be very helpful 🙇 

Closing in the meantime as I'm still unable to reproduce this.
