### ISSUE TITLE
Error in v2.0.2 with UglifyJS

### ISSUE THREAD

**Issue by planetflash** [lukeed/sockette#41]
When I run our build with v2.0.2 or v2.0.3 I get the following error message. However, if I run with v2.0.1 our project builds without error.
```
ERROR in 13.ce2f3dc9b0373574d554.chunk.js from UglifyJs
Unexpected token: operator (>) [/work/node_modules/sockette/dist/sockette.js:30,0][13.ce2f3dc9b0373574d554.chunk.js:2646,32]
Child html-webpack-plugin for "index.html":
     1 asset
```
I have tried updating to the latest `html-webpack-plugin` in case that was an issue, but it doesn't seem to be.

**Comment by lukeed** [comment]
Oops! I missed a fat-arrow function when changing the build tools.

Thanks!
