### ISSUE TITLE
onerror not returning code

### ISSUE THREAD

**Issue by Eli-Black-Work** [lukeed/sockette#45]
Hello,

The documentation for `onerror` says "Important: If the event.code is ECONNREFUSED, an automatic reconnect attempt will be queued."

However, when doing `onerror: e => console.log('Error:', e)`, it looks like `e.code` doesn't exist.

**Comment by lukeed** [comment]
It's not meant to have a `code` key – it _can_ & _when it is_ a ECONNREFUSED code, a reconnect will be attempted.

The `onerror` (primarily) receives [Events or ErrorEvents](https://html.spec.whatwg.org/multipage/indices.html#event-error). It's the [`CloseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) (via `onclose`) that will always have a numerical `code` property. Sockette will reconnect if the connection was _not_ closed with a `code` of 1000 or 1005.

Hope that helps a bit~!

**Comment by Eli-Black-Work** [comment]
Thanks, @lukeed  :)
