### ISSUE TITLE
Still reconnecting after close()

### ISSUE THREAD

**Issue by raduciobanu22** [lukeed/sockette#49]
I just tested v2.0.5 and unfortunately the issue is still there. This is my scenario:
1. Open WS connection A.
2. Close WS connection A.
3. Open WS connection B.
4. Close WS connection B.
5. Open WS connection C.

After a while WS connections A and B are reopened. They are initially closed, but re-opened.

**Comment by lukeed** [comment]
v2.0.5 does not include 66bf604 – I've not published a new version yet.

If you could paste in the most recent code from master & test it out, that'd be appreciated

**Comment by raduciobanu22** [comment]
Sure, give me a sec.

**Comment by raduciobanu22** [comment]
Problem still seems to be there.
This is the scenario:
1. Open WS connection A.
2. Close WS connection A.
3. Open WS connection B.
4. Close WS connection B.
5. Open WS connection C.

Another interesting aspect is that calling close() does not trigger the onclose callback.
But after a while (10+ seconds) I am seeing that callback being triggered and the code is 1006. Right after that the connections that were previously closed are reopened one by one.

**Comment by raduciobanu22** [comment]
@lukeed Ignore my previous comment. The issue is fixed. It does not reconnect anymore after calling close(). The last part with the onclose callback being called with code 1006 is still there but the main issue is fixed.

**Comment by lukeed** [comment]
Cool, thanks

I need a repro for the second half. Sounds like #29
Way too many variables involved. Servers can be acting up, the action you take on client side can be interpreted any number of ways, etc
