### ISSUE TITLE
Socks emoji in readme is missing on macOS Sierra

### ISSUE THREAD

**Issue by jdanford** [lukeed/sockette#9]
<img width="325" alt="screen shot of sadness" src="https://user-images.githubusercontent.com/5767112/35737233-12348686-07e8-11e8-8035-ba500b7b100e.png">
I can't see the cuteness 😞

**Comment by AndrewSouthpaw** [comment]
I think this is critical to being able to use the library.

**Comment by lukeed** [comment]
Lol yeah, it's critical! Unfortunately it's because socks was part of the latest emoji batch...took me a while to figure out why GitHub didn't have it either.

IMO it's still worth the gamble 😅 GitHub will have it soon enough...I hope
